# import matplotlib.pyplot as plt
# import numpy as np

# xpoints = np.array([0, 10000])
# ypoints = np.array([0, 10000])

# plt.plot(xpoints*xpoints, ypoints*xpoints)
# plt.show()

from turtle import *
forward(240)
left(90)
forward(240)
left (90)
forward(240)
left(90)
forward(240)
color('red')
fill(2)


input("press :")

reset()
a = 0 
while a <12:
    a = a +1
    forward(150)
    left(150)